apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retail-pvc
  namespace: pavi18-ns
spec:
  storageClassName: nfs-retail
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi